### ISSUE TITLE
enrollment utterances？

### ISSUE THREAD

**Issue by JJun-Guo** [wngh1187/RawNeXt#3]
hi,how many utterances need to enrolment in the eval statment?

**Comment by wngh1187** [comment]
Hi. Thank you for your interest in my research. 
I used VoxCeleb1 official 3 test sets.
The original evaluation trial (Vox1-O) needs 4,874 utterances from 40 speakers.
The extended (Vox1-E) and hard (Vox1-E) evaluation trials need 145,160 and 137,924  utterances from 1,251 and 1,190 speakers.

**Comment by JJun-Guo** [comment]
> 

yes!  do u mean that for Vox1-O we need 4,874 from 40 speakers to enrolment( more 100 utterances per person), and then choose some other utterances to predict? can we choose few utterances(such as 10 utterances) to enrolment and reach the perfect performance?

**Comment by wngh1187** [comment]
Vox1-O trial included 37,720 pairs (enroll-test utts) using 4,874 utterances. 
Therefore, we do not use any utterances other than the 4,874 utterances for evaluation of the Vox1-O trial.
And, we did not evaluate with few utterances because we only evaluated the official trials.
To evaluate the model with few utterances, I think you should make a separate mini-trial.

**Comment by JJun-Guo** [comment]
> 

GET！ thanks for your answer, i have another question that do you apply the voice avtivity dection(VAD) to process the dataset?

**Comment by wngh1187** [comment]
We are happy to answer your question!
Also, we did not use any VAD :)
